# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=32)),
                ('client_secret', models.CharField(max_length=32)),
                ('redirect_uri', models.CharField(max_length=255)),
            ],
        ),
    ]
