# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0002_instagramclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlickrClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=32)),
                ('secret_key', models.CharField(max_length=16)),
            ],
        ),
    ]
