# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0003_flickrclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramClient',
        ),
    ]
