# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0004_delete_instagramclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlickrPost',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=32)),
                ('farm', models.PositiveSmallIntegerField()),
                ('server', models.PositiveSmallIntegerField()),
                ('owner', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('image_url', models.CharField(max_length=512)),
            ],
        ),
    ]
