# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0005_flickrpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrpost',
            name='date_fetched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flickrpost',
            name='search_term',
            field=models.CharField(default='foo', max_length=64),
            preserve_default=False,
        ),
    ]
