# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0007_auto_20160403_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrpost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='flickrpost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
