# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0011_yelpclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrpost',
            name='page',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
