# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entree', '0012_flickrpost_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram_auth_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='search_radius',
        ),
    ]
